### PR TITLE
second attempt at the branch

### PR DESCRIPTION
**Pull request by JaivePNG**
This is my second attempt. Maybe I should have created a master branch first. Changes to Tidying.

### CODE REVIEW

**Comment by joseph-code-EDA** [comment]
Hey Jaive,
Here are somethings I picked up on.
Line 72 - closing footer not aligned with opening footer tag
Line 85 - indent `<a>`anchors
Line 82 - indent `<nav role...>`
Line 131 - indent `<ul>`
Line 54 - watch out for over indentation

Tags like `<body>, <head>`should be in column 1 - the beginning of each line
Indent all `<p>`paragraphs

Line 39 - take back one indentation - needs to line up with closing `</div>` on Line 74
Line 77-78 - need to line up with Lines 150-151

**Comment by joseph-code-EDA** [comment]
Still need to indent paragraphs

**Comment by JaivePNG** [comment]
Hi Joseph, have a look at this latest series of indentation. Thanks.

**Comment by joseph-code-EDA** [comment]
Awesome work Jaive, your code is much clearer.
Only one more recommendation and that's to indent the `<ul>...</ul>` and it's nested contents between the `<nav>`s.
Once done I'll do the merge pull request

**Comment by joseph-code-EDA** [comment]
Am happy with the edits made Jaive,will merge your pull request :+1:

**Pull request merged**
